CREATE TABLE DPURGE
(
    ID        RAW (16)        NOT NULL,
    REQUESTOR RAW (16)        NOT NULL,
    STATUS    VARCHAR(50) NOT NULL
) LOGGING;

CREATE TABLE DPURGE_ENTRY
(
    ID            RAW (16)        NOT NULL,
    DPURGE        RAW (16)        NOT NULL,
    RESOURCE_NODE RAW (16),
    ENTITY_ID     VARCHAR(50),
    PATH          VARCHAR(4000),
    STATUS        VARCHAR(50) NOT NULL,
    STATUS_MSG    VARCHAR(4000)
) LOGGING;

CREATE TABLE DPURGE_VERSION
(
    ID RAW (16) NOT NULL
) LOGGING;

CREATE TABLE DPURGE_REVIEWER
(
    ID       RAW (16)       NOT NULL,
    DPURGE   RAW (16)       NOT NULL,
    APP_USER RAW (16)       NOT NULL,
    SIGNED   NUMERIC(1) NOT NULL
) LOGGING;



ALTER TABLE DPURGE
    ADD CONSTRAINT DPURGE_PK PRIMARY KEY (ID);

ALTER TABLE DPURGE_ENTRY
    ADD CONSTRAINT DPURGE_ENTRY_PK PRIMARY KEY (ID);

ALTER TABLE DPURGE_VERSION
    ADD CONSTRAINT DPURGE_VERSION_PK PRIMARY KEY (ID);

ALTER TABLE DPURGE_REVIEWER
    ADD CONSTRAINT DPURGE_REVIEWER_PK PRIMARY KEY (ID);

ALTER TABLE DPURGE
    ADD CONSTRAINT DPURGE_INHERITANCE
        FOREIGN KEY (ID) REFERENCES RESOURCE_NODE (ID) ON DELETE CASCADE;

ALTER TABLE DPURGE
    ADD CONSTRAINT DPURGE_REQUESTOR
        FOREIGN KEY (REQUESTOR) REFERENCES auth_member (ID) NOT DEFERRABLE;

ALTER TABLE DPURGE_ENTRY
    ADD CONSTRAINT DPURGE_ENTRY_DPURGE
        FOREIGN KEY (DPURGE) REFERENCES RESOURCE_NODE (ID) NOT DEFERRABLE;

ALTER TABLE DPURGE_ENTRY
    ADD CONSTRAINT DPURGE_ENTRY_RESOURCE
        FOREIGN KEY (RESOURCE_NODE) REFERENCES RESOURCE_NODE (ID) NOT DEFERRABLE;

ALTER TABLE DPURGE_VERSION
    ADD CONSTRAINT DPURGE_VERSION_INHERITANCE
        FOREIGN KEY (ID) REFERENCES RESOURCE_NODE_VERSION (ID) ON DELETE CASCADE;

ALTER TABLE DPURGE_REVIEWER
    ADD CONSTRAINT DPURGE_REVIEWER_DPURGE
        FOREIGN KEY (DPURGE) REFERENCES RESOURCE_NODE (ID) NOT DEFERRABLE;

ALTER TABLE DPURGE_REVIEWER
    ADD CONSTRAINT DPURGE_REVIEWER_APP_USER
        FOREIGN KEY (APP_USER) REFERENCES auth_member (ID) NOT DEFERRABLE;

CREATE INDEX DPURGE_ENTRY_DPURGE ON DPURGE_ENTRY (DPURGE ASC);
CREATE INDEX DPURGE_ENTRY_RESOURCE_IDX ON DPURGE_ENTRY (RESOURCE_NODE);

INSERT INTO ENTITY_TYPE (ID, TYPE, DESCRIPTION, TABLE_NAME, ENTITY_ABBREV, CONTAINER)
VALUES ('3652F1D04C65447D94D5134CDB82358E', 'PU', 'Purge', 'DPURGE', 'PU', 0);
INSERT INTO ENTITY_TYPE (ID, TYPE, DESCRIPTION, TABLE_NAME, ENTITY_ABBREV, CONTAINER)
VALUES ('111E2491FC28469EB61626CC6786A3BD', 'PUV', 'Purge Version', 'DPURGE_VERSION', 'PUV', 0);

